Script done

diff --git a/asus-health-charging b/asus-health-charging
--- a/asus-health-charging
+++ b/asus-health-charging
@@ -1,8 +1,56 @@
-# If manually launched:
-    # Ask which percentage the user wants to maintain
-    # Write to ~/.config/asus-health-charging.conf
-    # Apply to system (write to /sys/class/power_supply/BAT*/charge_control_end_threshold)
+#! /bin/sh
 
-# If launched by the system (--restore):
-    # Read from ~/.config/asus-health-charging.conf
-    # Apply to system (write to /sys/class/power_supply/BAT*/charge_control_end_threshold)
+# Configuration files
+PERCENTAGE_FILE="/etc/asus-health-charging.d/percentage"
+INTERFACE_FILE="/etc/asus-health-charging.d/interface"
+
+# Base function
+setter () {
+	if (( $1 >= 15 && $1 <= 100 ))
+	then
+		ASUS_HEALTH_PERCENTAGE=$1
+		echo "$ASUS_HEALTH_PERCENTAGE" > "$PERCENTAGE_FILE"
+		echo "$ASUS_HEALTH_PERCENTAGE" > "$ASUS_HEALTH_INTERFACE"
+	else
+		>&2 echo "asus-health-charging: invalid parameter"
+		>&2 echo "asus-health-charging: set a percentage beetween 15 and 100"
+		exit 1
+	fi
+}
+
+# Interface check
+if [[ ! -f "$INTERFACE_FILE" ]]
+then
+	>&2 echo "asus-health-charging: \"$INTERFACE_FILE\" file not found"
+	exit 1
+fi
+
+ASUS_HEALTH_INTERFACE=$(cat "$INTERFACE_FILE")
+
+if [[ ! -f "$ASUS_HEALTH_INTERFACE" ]]
+then
+	>&2 echo "asus-health-charging: \"$ASUS_HEALTH_INTERFACE\" file not found"
+	exit 1
+fi
+# End of interface check
+
+# Parameter check
+case $1 in
+"--current")
+	cat "$ASUS_HEALTH_INTERFACE"
+	;;
+"--restore")
+	if [[ -f "$PERCENTAGE_FILE" ]]
+	then
+	    echo "asus-health-charging: Restoring from configuration"
+		setter $(cat "$PERCENTAGE_FILE")
+	else
+		>&2 echo "asus-health-charging: \"$PERCENTAGE_FILE\" file not found"
+		>&2 echo "asus-health-charging: reverting to default value 100%"
+		setter 100
+	fi
+	;;
+*)
+	setter $1
+	;;
+esac
